# Add Pydantic schemas here that you'll use in your routes / endpoints
# Pydantic schemas are used to validate data that you receive, or to make sure that whatever data
# you send back to the client follows a certain structure

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime, time
from decimal import Decimal

#-----------------#
#-----BUSINESS----#
#-----------------#
class BusinessBase(BaseModel):
    """
    Shared fields used by both creation and update operations for business.
    """
    main_category_id: Optional[int] = None
    name: str
    description: Optional[str] = None
    street_name: Optional[str] = None
    street_number: Optional[str] = None
    city: Optional[str] = None
    postal_code: Optional[str] = None


#I put owner_id only in the POST/PUT models because it is not a 
# core attribute of the business — it is a foreign key that 
# #is only relevant when creating or updating a business and does not
# #effect the identity of the business.
class BusinessCreate(BusinessBase):
    """
    Used when a client creates a new business (POST).
    Requires the owner_id and name fields, other fields are optional.
    """
    owner_id: int

class BusinessUpdate(BusinessBase):
    """
    Used for full replacement of a business (PUT).
    All required fields must be included and will overwrite existing values.
    """
    owner_id: int

class BusinessOut(BusinessBase):
    """
    Returned to the client when reading business data (GET).
    Includes database-generated fields such as id and created_at.
    """
    id: int
    owner_id: int
    created_at: datetime


#-----------------#
#-------USERS-----#
#-----------------#

class UserBase(BaseModel):
    """
    Shared fields used by both creation and update operations for users.
    """
    role: str
    firstname: str
    lastname: str
    username: str
    email: str
    phone_number: Optional[str] = None
    
class UserCreate(UserBase):
    """
    Schema used when someone registers or when a provider/admin account is created.
    All fields except phone_number are required.
    """
    pass

class UserUpdate(UserBase):
    """
    Schema used for full replacement of a user (PUT).
    """
    pass

class UserOut(UserBase):
    """
    Schema returned when fetching user information from the API.
    Includes database-generated fields such as id and created_at.
    """
    id: int
    created_at: datetime
    
#-----------------#
#----CATEGORIES---#
#-----------------#

class CategoryBase(BaseModel):
    """
    Base attributes shared across category operations.
    """
    name: str
    description: Optional[str] = None
    parent_id: Optional[int] = None

class CategoryCreate(CategoryBase):
    """
    Schema used when creating a new category.
    Required: name
    Optional: description, parent_id
    """
    pass

class CategoryUpdate(CategoryBase):
    """
    Full replacement of a category (PUT).
    """
    pass

class CategoryOut(CategoryBase):
    """
    Returned when fetching category data.
    Adds database-generated fields.
    """
    id: int


#-----------------#
#--STAFF MEMBERS--#
#-----------------#

class StaffMemberBase(BaseModel):
    """
    Core attributes for a staff member belonging to a business.
    """
    business_id: int
    name: str
    email: str
    phone_number: Optional[str] = None
    role: Optional[str] = None
    is_active: bool = True


class StaffMemberCreate(StaffMemberBase):
    """
    Used when creating a new staff member (POST).
    All base fields except phone_number and role can be required at the DB level.
    """
    pass


class StaffMemberUpdate(StaffMemberBase):
    """
    Used for full replacement of a staff member (PUT).
    All fields will overwrite existing values.
    """
    pass


class StaffMemberOut(StaffMemberBase):
    """
    Returned when reading staff member data (GET).
    Includes the autogenerated id.
    """
    id: int
    
    
#------------------#
#-BUISSNESS IMAGES-#
#------------------#

class BusinessImageBase(BaseModel):
    """
    Base attributes shared between creation and update of business images.
    """
    business_id: int
    image_url: str
    is_logo: bool = False
    sort_order: int = 0
class BusinessImageCreate(BusinessImageBase):
    """
    Used when adding a new image to a business.
    """
    pass
class BusinessImageUpdate(BusinessImageBase):
    """
    Used in PUT when fully replacing an existing image entry.
    """
    pass
class BusinessImageOut(BusinessImageBase):
    """
    Schema returned when fetching business images.
    Includes the generated ID.
    """
    id: int

#-----------------#
#--OPENING HOURS--#
#-----------------#

class OpeningHoursEntry(BaseModel):
    weekday: int   # 1–7
    open_time: time
    closing_time: time

class OpeningHoursUpdateRequest(BaseModel):
    """
    Used to REPLACE all opening hours for a business.
    The client must send a full list of weekday entries.
    """
    hours: list[OpeningHoursEntry]

class OpeningHoursOut(BaseModel):
    id: int
    business_id: int
    weekday: int
    open_time: time
    closing_time: time

#-----------------#
#-----SERVICES----#
#-----------------#

class ServiceBase(BaseModel):
    name: str
    description: Optional[str] = None
    duration_minutes: int
    price: float
    is_active: Optional[bool] = True


class ServiceCreate(ServiceBase):
    """Schema used when creating a service (POST)."""
    business_id: int


class ServiceUpdate(ServiceBase):
    """Schema used when fully updating (PUT) a service."""
    business_id: int
    
#-----------------#
#-----BOOKINGS----#
#-----------------#

class BookingBase(BaseModel):
    customer_id: int
    business_id: int
    service_id: int
    staff_id: Optional[int] = None
    starttime: datetime
    endtime: datetime
    status: str = "pending"
    notes: Optional[str] = None

class BookingCreate(BookingBase):
    """Used when creating a new booking."""
    pass

class BookingUpdate(BookingBase):
    """Used when fully updating a booking."""
    pass

class BookingStatusUpdate(BaseModel):
    status: str  # must be one of your allowed values
    status: str = Field(
        ...,
        pattern="^(pending|confirmed|cancelled|completed)$"
    )

#-----------------#
#-----PAYMENTS----#
#-----------------#

class PaymentBase(BaseModel):
    booking_id: Optional[int] = None
    amount: Decimal
    payment_method: str
    status: str = Field(
        "pending",
        pattern="^(pending|paid|refunded|failed)$"
    )


class PaymentCreate(PaymentBase):
    """
    Used when creating a new payment.
    booking_id is required in practice, but made optional in case of edge cases.
    """
    booking_id: int


class PaymentOut(PaymentBase):
    """
    Returned when reading payment data.
    """
    id: int
    created_at: datetime

class PaymentStatusUpdate(BaseModel):
    status: str = Field(
        ...,
        pattern="^(pending|paid|refunded|failed)$"
    )
